---

# Redis uses a mix of sha1 and sha256 checksums.
# Determine the type of checksum based on its length and prefix the variable appropriately
- name: set redis checksum
  set_fact:
    redis_checksum: "{{ 'sha1' if redis_checksums[redis_version]|length == 40 else 'sha256' }}:{{ redis_checksums[redis_version] }}"
  when:
    - redis_verify_checksum|bool
    - redis_checksum is not defined
    - redis_version in redis_checksums

- name: create a temporary download target directory
  tempfile:
    state: directory
    suffix: download
  register: download_target

- name: download redis
  get_url:
    url: "{{ redis_download_url }}"
    dest: "{{ download_target.path }}/redis-{{ redis_version }}.tar.gz"
    checksum: "{{ redis_checksum|default(omit) }}"
  when: not redis_tarball

- name: upload redis
  copy:
    src: "{{ redis_tarball }}"
    dest: "{{ download_target.path }}/redis-{{ redis_version }}.tar.gz"
  when: redis_tarball|default(false)

- name: extract redis tarball
  unarchive:
    src: "{{ download_target.path }}/redis-{{ redis_version }}.tar.gz"
    dest: /usr/local/src
    creates: /usr/local/src/redis-{{ redis_version }}/Makefile
    remote_src: true
  become: true
  when: not ansible_check_mode
